### ISSUE TITLE
Problem with the dataset

### ISSUE THREAD

**Issue by hodgechung** [YuankaiQi/ORIST#1]
There are corrupted files in your processed data, could you please check these two files?
![图片](https://user-images.githubusercontent.com/27922189/145553518-35ef972c-533e-4b26-947d-7272ec68ac1e.png)

**Comment by YuankaiQi** [comment]
Thanks for the feedback. I have updated it and please try again.

**Comment by hodgechung** [comment]
This line cannot be referenced, is there any omission of the code in the folder *data*?
https://github.com/YuankaiQi/ORIST/blob/f1d5cc747691f077c67b491a7eeb18f985050dfb/agent_r2r_multiloss.py#L20

**Comment by YuankaiQi** [comment]
updated

**Comment by hodgechung** [comment]
Have you encountered this error? 
```bash
Traceback (most recent call last):
  File "train_r2r_multiloss.py", line 782, in <module>
    train_val()
  File "train_r2r_multiloss.py", line 660, in train_val
    train(train_env, tok, val_envs=val_envs)
  File "train_r2r_multiloss.py", line 363, in train
    listner.train_with_grad_accumulate(1, feedback=feedback_method, batch_ids=batch_ids)  # Train interval iters
  File "/workspace/ORIST/agent_r2r_multiloss.py", line 985, in train_with_grad_accumulate
    self.rollout(train_ml=None, train_rl=True, **kwargs)
  File "/workspace/ORIST/agent_r2r_multiloss.py", line 673, in rollout
    self.process_mini_batchs(obs, train_rl, t)
  File "/workspace/ORIST/agent_r2r_multiloss.py", line 486, in process_mini_batchs
    next_region_logits, target_region_logits, self.state_c0 = self.model(train_rl,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 606, in forward
    if self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train_r2r_multiloss.py', '--local_rank=0', '--n_gpu', '3', '--train', 'listener', '--name', 'r2r-multiloss', '--task', 'R2R', '--project', 'orist', '--maxAction', '10', '--train_batch_size', '2', '--val_batch_size', '128', '--max_bb', '10', '--config', 'config/train-r2r-multiloss.json', '--drop_region_feat', '--region_drop_p', '0.5', '--use_lstm', '--mlWeight', '0.2', '--progress_loss', '--angle_loss', '--next_region_loss', '--target_region_loss', '--pretrained_model', 'pretrained/uniter-base.pt']' returned non-zero exit status 1.
```

**Comment by YuankaiQi** [comment]
No. It runs well with the docker image.
